packages:
  - app
  - core
  - design-tokens
  - services/*

catalog:
  '@eslint/js': 9.39.1
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@typescript-eslint/eslint-plugin': 8.48.0
  '@typescript-eslint/parser': 8.48.0
  eslint: ^9.39.2
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.4
  prettier: ^3.7.4
  typescript: 5.9.3
  typescript-eslint: 8.48.0

linkWorkspacePackages: true
